# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_all_grade.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,  QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtSql import QSqlQuery, QSqlDatabase, QSqlQueryModel
from PyQt5.QtWidgets import QHeaderView, QMenu
from all_functions import *
COLUMN_NAME=['学号','姓名','性别','专业','电话号码','班级','高级程序语言','python编程','数据库原理','数据结构与算法','数学分析',
             '高等数学','网络爬虫','数据可视化','数据挖掘','数据分析','总成绩']




class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)

        self.inimodel()
        self.pushButton.clicked.connect(self.filter_object)




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(687, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 2)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 5)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(341, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 4, 1, 1)
        self.pushButton.raise_()
        self.comboBox.raise_()
        self.pushButton_4.raise_()
        self.comboBox_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.tableView.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.pushButton_4.setText(_translate("MainWindow", "返回"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">平均成绩：</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))

    #初始化
    def inimodel(self):
        db= QSqlDatabase.addDatabase("QMYSQL")
        db.setHostName("127.0.0.1")
        db.setPort(3306)
        db.setDatabaseName("students")
        db.setUserName("root")
        db.setPassword("hsy010424")
        db.open()
        self.query=QSqlQuery()
        self.comboBox.clear()
        self.comboBox_2.clear()
        self.comboBox.addItems(get_classes_list(self.query))
        self.comboBox_2.addItems(COLUMN_NAME[6:-1])
        self.querymodel=QSqlQueryModel()
        sql="SELECT `姓名`,`性别`,`专业`,`电话号码`,`班级`,%s,`总成绩` FROM students WHERE 班级='%s'"%(self.comboBox_2.currentText(),self.comboBox.currentText())
        self.querymodel.setQuery(sql)
        self.tableView.setModel(self.querymodel)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.label_2.setText(str(avg_grade(get_informations(self.querymodel))))
        self.tableView.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableView.customContextMenuRequested.connect(self.generateMenu)
    #升降排序
    def generateMenu(self,pos):
        if self.tableView.currentIndex().column()>4:
            menu=QMenu()
            item1=menu.addAction(u"升序排列")
            item2=menu.addAction(u"降序排列")
            action=menu.exec_(self.tableView.mapToGlobal(pos))
            header=self.querymodel.headerData(self.tableView.currentIndex().column(),Qt.Horizontal)

            if action==item1:
                self.querymodel.setQuery("SELECT `姓名`,`性别`,`专业`,`电话号码`,`班级`,%s,`总成绩` FROM students WHERE 班级='%s' ORDER BY %s ASC"%(self.comboBox_2.currentText(),self.comboBox.currentText(),header))
            if action==item2:
                self.querymodel.setQuery("SELECT `姓名`,`性别`,`专业`,`电话号码`,`班级`,%s,`总成绩` FROM students WHERE 班级='%s' ORDER BY %s DESC"%(self.comboBox_2.currentText(),self.comboBox.currentText(),header))


    #查找信息和平均成绩的显示
    def filter_object(self):
        self.querymodel.setQuery("SELECT `姓名`,`性别`,`专业`,`电话号码`,`班级`,%s,`总成绩` FROM students WHERE 班级='%s'"%(self.comboBox_2.currentText(),self.comboBox.currentText()))
        self.label_2.setText(str(avg_grade(get_informations(self.querymodel))))
